[workspace]
resolver = "3"
members = ["a1", "a2", "a3", "a4", "a5", "a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "a16", "a17", "a18", "support/solid-core"]
default-members = ["a4"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"

[workspace.dependencies]
tempfile = "=3.27.0"

[workspace.lints.rust]
unsafe_code = "deny"

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
overflow-checks = true

[profile.test]
opt-level = 2

[profile.dev.package.argon2]
opt-level = 3
[profile.dev.package.blake2]
opt-level = 3
